// <auto-generated />
using System;
using ConntectLive.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConntectLive.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260921235639_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ConntectLive.DAL.QuestionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("Choices")
                        .HasColumnType("TEXT")
                        .HasColumnName("choices");

                    b.Property<string>("CorrectAnswer")
                        .HasColumnType("TEXT")
                        .HasColumnName("correct-answer");

                    b.Property<string>("Question")
                        .HasColumnType("TEXT")
                        .HasColumnName("question");

                    b.Property<Guid?>("UserEntityId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserEntityId");

                    b.ToTable("questions");
                });

            modelBuilder.Entity("ConntectLive.DAL.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT")
                        .HasColumnName("firstname");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT")
                        .HasColumnName("lastname");

                    b.Property<string>("Nickname")
                        .HasColumnType("TEXT")
                        .HasColumnName("nickname");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("ConntectLive.DAL.QuestionEntity", b =>
                {
                    b.HasOne("ConntectLive.DAL.UserEntity", null)
                        .WithMany("Questions")
                        .HasForeignKey("UserEntityId");
                });

            modelBuilder.Entity("ConntectLive.DAL.UserEntity", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
